#!/usr/bin/env sh
# Copyright 2026 John Wilger

set -eu

if [ -z "${GIT_TOKEN:-}" ]; then
  echo "GIT_TOKEN must be set before creating the release PR" >&2
  exit 1
fi

if [ -z "${GITHUB_REPOSITORY:-}" ]; then
  echo "GITHUB_REPOSITORY must be set before creating the release PR" >&2
  exit 1
fi

server_url="${GITHUB_SERVER_URL:-https://git.johnwilger.com}"
repository_owner="${GITHUB_REPOSITORY%%/*}"
repository_name="${GITHUB_REPOSITORY#*/}"
base_branch="${GITHUB_REF_NAME:-main}"
api_url="$server_url/api/v1/repos/$repository_owner/$repository_name"
branch_prefix="${RELEASE_PLZ_PR_BRANCH_PREFIX:-release-plz-}"
pr_title="${RELEASE_PLZ_PR_TITLE:-chore: release}"

release-plz update --forge gitea

if [ -z "$(git status --porcelain)" ]; then
  echo "release-plz found no release PR changes"
  exit 0
fi

open_pulls="$(
  curl -fsS \
    -H "Authorization: token $GIT_TOKEN" \
    "$api_url/pulls?state=open&limit=50"
)"

existing_release_pr="$(
  printf '%s' "$open_pulls" \
    | jq -r --arg prefix "$branch_prefix" 'map(select(.head.ref | startswith($prefix))) | sort_by(.number) | last | .number // empty'
)"

if [ -n "$existing_release_pr" ]; then
  release_branch="$(
    printf '%s' "$open_pulls" \
      | jq -r --argjson number "$existing_release_pr" '.[] | select(.number == $number) | .head.ref'
  )"
else
  release_branch="$branch_prefix$(date -u '+%Y-%m-%dT%H-%M-%SZ')"
fi

git switch -c "$release_branch"
git add -A
git commit -m "$pr_title"

if ! git cat-file commit HEAD | grep -q '^gpgsig '; then
  echo "release PR commit was not signed" >&2
  exit 1
fi

if [ -n "$existing_release_pr" ]; then
  git push --force-with-lease origin "HEAD:$release_branch"
  echo "updated release PR #$existing_release_pr"
else
  git push origin "HEAD:$release_branch"
  pr_body="Summary
- Release generated by release-plz after changes merged to main.

Verification
- release-plz update --forge gitea
- signed release PR commit created by Forgejo Actions"
  payload="$(
    jq -n \
      --arg base "$base_branch" \
      --arg head "$release_branch" \
      --arg title "$pr_title" \
      --arg body "$pr_body" \
      '{base: $base, head: $head, title: $title, body: $body}'
  )"

  curl -fsS \
    -X POST \
    -H "Authorization: token $GIT_TOKEN" \
    -H "Content-Type: application/json" \
    --data "$payload" \
    "$api_url/pulls" \
    | jq -r '"created release PR #\(.number): \(.html_url)"'
fi
