//! Commands for the bank demo. Each command implements `CommandLogic` with a
//! pure `apply` (fold events into write-model state) and a pure `handle`
//! (validate preconditions, produce new events). Stream declarations are
//! generated by `#[derive(Command)]`.
//!
//! The write-model state lives entirely here; it is never reused by the read
//! models in `projections.rs` (CQRS separation).

use eventcore::{Command, CommandError, CommandLogic, Event, NewEvents, StreamId};

use crate::domain::{AccountHolder, BankEvent, MoneyAmount};

// =============================================================================
// Business-rule errors
// =============================================================================

/// Business-rule violations for opening an account.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum OpenAccountError {
    #[error("account-already-open")]
    AlreadyOpen,
}

impl From<OpenAccountError> for CommandError {
    fn from(error: OpenAccountError) -> Self {
        CommandError::BusinessRuleViolation(Box::new(error))
    }
}

/// Business-rule violations for depositing money.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DepositError {
    #[error("account-not-open")]
    AccountNotOpen,
}

impl From<DepositError> for CommandError {
    fn from(error: DepositError) -> Self {
        CommandError::BusinessRuleViolation(Box::new(error))
    }
}

/// Business-rule violations for withdrawing money.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum WithdrawError {
    #[error("account-not-open")]
    AccountNotOpen,
    #[error("insufficient-funds")]
    InsufficientFunds,
}

impl From<WithdrawError> for CommandError {
    fn from(error: WithdrawError) -> Self {
        CommandError::BusinessRuleViolation(Box::new(error))
    }
}

/// Business-rule violations for transferring money between accounts.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum TransferError {
    #[error("same-account-transfer")]
    SameAccount,
    #[error("source-account-not-open")]
    SourceNotOpen,
    #[error("destination-account-not-open")]
    DestinationNotOpen,
    #[error("insufficient-funds")]
    InsufficientFunds,
}

impl From<TransferError> for CommandError {
    fn from(error: TransferError) -> Self {
        CommandError::BusinessRuleViolation(Box::new(error))
    }
}

// =============================================================================
// Write-model state
// =============================================================================

/// Write-model state for a single account, reconstructed from its stream.
///
/// Fields are private; behavior is exposed through intent-revealing methods.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct AccountState {
    is_open: bool,
    balance_cents: u32,
}

impl AccountState {
    fn open(mut self) -> Self {
        self.is_open = true;
        self
    }

    fn credit(mut self, amount: MoneyAmount) -> Self {
        let cents: u32 = amount.into();
        self.balance_cents = self.balance_cents.saturating_add(cents);
        self
    }

    fn debit(mut self, amount: MoneyAmount) -> Self {
        let cents: u32 = amount.into();
        self.balance_cents = self.balance_cents.saturating_sub(cents);
        self
    }

    fn is_open(&self) -> bool {
        self.is_open
    }

    fn has_sufficient_funds(&self, amount: MoneyAmount) -> bool {
        let cents: u32 = amount.into();
        self.balance_cents >= cents
    }

    /// Fold a single event into the account state (write model).
    fn apply(self, event: &BankEvent) -> Self {
        match event {
            BankEvent::AccountOpened { .. } => self.open(),
            BankEvent::MoneyDeposited { amount, .. } => self.credit(*amount),
            BankEvent::MoneyWithdrawn { amount, .. } => self.debit(*amount),
        }
    }
}

/// Write-model state for a transfer, tracking both the source and destination
/// accounts as events from both streams are folded in.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct TransferState {
    source: AccountState,
    destination: AccountState,
}

// =============================================================================
// Commands
// =============================================================================

/// Open a new bank account on its own stream.
#[derive(Command)]
pub struct OpenAccount {
    #[stream]
    pub account_id: StreamId,
    pub holder: AccountHolder,
}

impl CommandLogic for OpenAccount {
    type Event = BankEvent;
    type State = AccountState;

    fn apply(&self, state: Self::State, event: &Self::Event) -> Self::State {
        state.apply(event)
    }

    fn handle(&self, state: Self::State) -> Result<NewEvents<Self::Event>, CommandError> {
        if state.is_open() {
            return Err(OpenAccountError::AlreadyOpen.into());
        }

        Ok(vec![BankEvent::AccountOpened {
            account_id: self.account_id.clone(),
            holder: self.holder.clone(),
        }]
        .into())
    }
}

/// Deposit money into an existing account.
#[derive(Command)]
pub struct Deposit {
    #[stream]
    pub account_id: StreamId,
    pub amount: MoneyAmount,
}

impl CommandLogic for Deposit {
    type Event = BankEvent;
    type State = AccountState;

    fn apply(&self, state: Self::State, event: &Self::Event) -> Self::State {
        state.apply(event)
    }

    fn handle(&self, state: Self::State) -> Result<NewEvents<Self::Event>, CommandError> {
        if !state.is_open() {
            return Err(DepositError::AccountNotOpen.into());
        }

        Ok(vec![BankEvent::MoneyDeposited {
            account_id: self.account_id.clone(),
            amount: self.amount,
        }]
        .into())
    }
}

/// Withdraw money from an existing account, rejecting overdrafts.
#[derive(Command)]
pub struct Withdraw {
    #[stream]
    pub account_id: StreamId,
    pub amount: MoneyAmount,
}

impl CommandLogic for Withdraw {
    type Event = BankEvent;
    type State = AccountState;

    fn apply(&self, state: Self::State, event: &Self::Event) -> Self::State {
        state.apply(event)
    }

    fn handle(&self, state: Self::State) -> Result<NewEvents<Self::Event>, CommandError> {
        if !state.is_open() {
            return Err(WithdrawError::AccountNotOpen.into());
        }
        if !state.has_sufficient_funds(self.amount) {
            return Err(WithdrawError::InsufficientFunds.into());
        }

        Ok(vec![BankEvent::MoneyWithdrawn {
            account_id: self.account_id.clone(),
            amount: self.amount,
        }]
        .into())
    }
}

/// Transfer money between two accounts atomically.
///
/// This is the centerpiece of the demo: declaring two `#[stream]` fields makes
/// the command read and write both streams within a single optimistic-concurrency
/// transaction. Either both the withdrawal AND the deposit are persisted, or
/// neither is.
#[derive(Command)]
pub struct Transfer {
    #[stream]
    pub from: StreamId,
    #[stream]
    pub to: StreamId,
    pub amount: MoneyAmount,
}

impl CommandLogic for Transfer {
    type Event = BankEvent;
    type State = TransferState;

    fn apply(&self, mut state: Self::State, event: &Self::Event) -> Self::State {
        if event.stream_id() == &self.from {
            state.source = state.source.apply(event);
        }
        if event.stream_id() == &self.to {
            state.destination = state.destination.apply(event);
        }
        state
    }

    fn handle(&self, state: Self::State) -> Result<NewEvents<Self::Event>, CommandError> {
        if self.from == self.to {
            return Err(TransferError::SameAccount.into());
        }
        if !state.source.is_open() {
            return Err(TransferError::SourceNotOpen.into());
        }
        if !state.destination.is_open() {
            return Err(TransferError::DestinationNotOpen.into());
        }
        if !state.source.has_sufficient_funds(self.amount) {
            return Err(TransferError::InsufficientFunds.into());
        }

        Ok(vec![
            BankEvent::MoneyWithdrawn {
                account_id: self.from.clone(),
                amount: self.amount,
            },
            BankEvent::MoneyDeposited {
                account_id: self.to.clone(),
                amount: self.amount,
            },
        ]
        .into())
    }
}
